

service: staircase-img-recognition-sls
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  profile: default
# you can overwrite defaults here
  stage: dev
  region: eu-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
    
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:

  GenerateUrl:
    handler: url.generateUrl
    memorySize: 128
    events:
      - httpApi:
          path: /img/requestUrl
          method: post
          cors: true
    environment:
      BUCKET_NAME: ${self:custom.bucket}
  
  imgRecognition:
    handler: recognition.imgRecognition
    memorySize: 128
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
    environment:
      TableName: ${self:resources.Resources.serviceTable.Properties.TableName} 
      BUCKET_NAME: ${self:custom.bucket}
  
  getLabels:
    handler: labels.getLabels
    memorySize: 256
    events:
      - httpApi:
          path: /img/{id}
          method: get
    environment:
      TableName: ${self:resources.Resources.serviceTable.Properties.TableName}
      
custom:
  bucket: staircase-tem-imgs-bucket-v1
    
resources:
  Resources:
    serviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: img_labels
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1